### ISSUE TITLE
Build fails with Elasticsearch 6.0.0-rc1

### ISSUE THREAD

**Issue by loren** [Automattic/elasticsearch-statsd-plugin#23]
This is just a heads up that there may be issues with ES6 when it releases. I ran the integration test suite against `6.0.0-rc1` and it failed with these two errors:
```
-------------------------------------------------------------------------------
Test set: com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest
-------------------------------------------------------------------------------
Tests run: 10, Failures: 2, Errors: 8, Skipped: 0, Time elapsed: 28.335 sec <<< FAILURE!
masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.262 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest.assertStatsdMetricIsContained(StatsdPluginIntegrationTest.java:124)
	at com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest.masterFailOverShouldWork(StatsdPluginIntegrationTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.277 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=16, name=elasticsearch[node_sm0][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.278 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=19, name=elasticsearch[node_sm1][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.279 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=22, name=elasticsearch[node_sm2][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.28 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=25, name=elasticsearch[node_sd3][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.281 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=28, name=elasticsearch[node_sd4][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.282 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=31, name=elasticsearch[node_sd5][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

masterFailOverShouldWork(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 14.283 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=229, name=elasticsearch[node_s6][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)

testThatIndexingResultsInMonitoring(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 3.119 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest.assertStatsdMetricIsContained(StatsdPluginIntegrationTest.java:124)
	at com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest.testThatIndexingResultsInMonitoring(StatsdPluginIntegrationTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:745)

testThatIndexingResultsInMonitoring(com.automattic.elasticsearch.statsd.test.StatsdPluginIntegrationTest)  Time elapsed: 3.12 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=282, name=elasticsearch[node_sm1][statsd_reporter][T#1], state=RUNNABLE, group=TGRP-StatsdPluginIntegrationTest]
Caused by: java.lang.AssertionError: initial cluster state not set yet
	at __randomizedtesting.SeedInfo.seed([F1C5FAF4F9C6FC35]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:190)
	at org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:135)
	at com.automattic.elasticsearch.statsd.StatsdService$StatsdReporterThread.run(StatsdService.java:118)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by loren** [comment]
Fixed by https://github.com/Automattic/elasticsearch-statsd-plugin/pull/26
