### ISSUE TITLE
Elasticsearch 7.x compatibility? (tested and failed on 7.5.1)

### ISSUE THREAD

**Issue by TomGudman** [Automattic/elasticsearch-statsd-plugin#35]
Hi,

**What?**
elasticsearch-statsd-plugin 6.1.8.0 is incompatible with Elasticsearch 7.5.1 despite modifying the version in `plugin-descriptor.properties`. 6.1.8.0 worked fine on ES 6.8.6.

**Errors**
```
[2020-01-06T04:20:45,469][INFO ][o.e.n.Node               ] [es-logs-data01] version[7.5.1], pid[13928], build[default/deb/3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96/2019-12-16T22:57:37.835892Z], OS[Linux/4.4.0-1017-aws/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]
[2020-01-06T04:20:45,469][INFO ][o.e.n.Node               ] [es-logs-data01] JVM home [/usr/share/elasticsearch/jdk]
[2020-01-06T04:20:45,469][INFO ][o.e.n.Node               ] [es-logs-data01] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms8g, -Xmx8g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-11057503640209381668, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=4294967296, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]
[2020-01-06T04:20:48,350][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [aggs-matrix-stats]
[2020-01-06T04:20:48,351][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [analysis-common]
[2020-01-06T04:20:48,351][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [flattened]
[2020-01-06T04:20:48,351][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [frozen-indices]
[2020-01-06T04:20:48,352][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [ingest-common]
[2020-01-06T04:20:48,352][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [ingest-geoip]
[2020-01-06T04:20:48,352][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [ingest-user-agent]
[2020-01-06T04:20:48,352][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [lang-expression]
[2020-01-06T04:20:48,353][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [lang-mustache]
[2020-01-06T04:20:48,353][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [lang-painless]
[2020-01-06T04:20:48,353][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [mapper-extras]
[2020-01-06T04:20:48,354][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [parent-join]
[2020-01-06T04:20:48,354][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [percolator]
[2020-01-06T04:20:48,354][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [rank-eval]
[2020-01-06T04:20:48,355][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [reindex]
[2020-01-06T04:20:48,355][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [repository-url]
[2020-01-06T04:20:48,355][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [search-business-rules]
[2020-01-06T04:20:48,356][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [spatial]
[2020-01-06T04:20:48,356][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [systemd]
[2020-01-06T04:20:48,356][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [transform]
[2020-01-06T04:20:48,357][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [transport-netty4]
[2020-01-06T04:20:48,357][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [vectors]
[2020-01-06T04:20:48,357][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-analytics]
[2020-01-06T04:20:48,357][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-ccr]
[2020-01-06T04:20:48,358][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-core]
[2020-01-06T04:20:48,358][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-deprecation]
[2020-01-06T04:20:48,358][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-enrich]
[2020-01-06T04:20:48,359][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-graph]
[2020-01-06T04:20:48,359][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-ilm]
[2020-01-06T04:20:48,359][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-logstash]
[2020-01-06T04:20:48,360][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-ml]
[2020-01-06T04:20:48,360][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-monitoring]
[2020-01-06T04:20:48,360][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-rollup]
[2020-01-06T04:20:48,360][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-security]
[2020-01-06T04:20:48,361][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-sql]
[2020-01-06T04:20:48,361][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-voting-only-node]
[2020-01-06T04:20:48,361][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded module [x-pack-watcher]
[2020-01-06T04:20:48,362][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded plugin [discovery-ec2]
[2020-01-06T04:20:48,362][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded plugin [repository-s3]
[2020-01-06T04:20:48,363][INFO ][o.e.p.PluginsService     ] [es-logs-data01] loaded plugin [statsd]
[2020-01-06T04:20:53,041][INFO ][o.e.x.s.a.s.FileRolesStore] [es-logs-data01] parsed [0] roles from file [/etc/elasticsearch/roles.yml]
[2020-01-06T04:20:53,644][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [es-logs-data01] [controller/13979] [Main.cc@110] controller (64 bit): Version 7.5.1 (Build ae3c3c51b849be) Copyright (c) 2019 Elasticsearch BV
[2020-01-06T04:20:54,195][DEBUG][o.e.a.ActionModule       ] [es-logs-data01] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2020-01-06T04:20:54,317][INFO ][o.e.d.DiscoveryModule    ] [es-logs-data01] using discovery type [zen] and seed hosts providers [settings, ec2]
[2020-01-06T04:20:55,165][ERROR][o.e.b.Bootstrap          ] [es-logs-data01] Exception
org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void org.elasticsearch.common.component.AbstractLifecycleComponent.<init>(org.elasticsearch.common.settings.Settings)'
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:769) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:799) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:594) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.5.1.jar:7.5.1]
Caused by: java.lang.NoSuchMethodError: 'void org.elasticsearch.common.component.AbstractLifecycleComponent.<init>(org.elasticsearch.common.settings.Settings)'
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:55) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:760) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:816) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:755) ~[elasticsearch-7.5.1.jar:7.5.1]
	... 20 more
[2020-01-06T04:20:55,179][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-logs-data01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void org.elasticsearch.common.component.AbstractLifecycleComponent.<init>(org.elasticsearch.common.settings.Settings)'
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.5.1.jar:7.5.1]
Caused by: org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'void org.elasticsearch.common.component.AbstractLifecycleComponent.<init>(org.elasticsearch.common.settings.Settings)'
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:769) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:799) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:594) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]
	... 6 more
Caused by: java.lang.NoSuchMethodError: 'void org.elasticsearch.common.component.AbstractLifecycleComponent.<init>(org.elasticsearch.common.settings.Settings)'
	at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:55) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl$4$1.call(InjectorImpl.java:760) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:816) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl$4.get(InjectorImpl.java:755) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.inject.InjectorImpl.getInstance(InjectorImpl.java:799) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:594) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]
	... 6 more
[2020-01-06T04:20:55,200][INFO ][o.e.x.m.p.NativeController] [es-logs-data01] Native controller process has stopped - no new native processes can be started
```

**Workaround**

1. Remove the plugin with `/usr/share/elasticsearch/bin/elasticsearch-plugin remove statsd`
2. Edit /etc/elasticsearch/elasticsearch.yml to remove any references to _metrics.*_
3. Then Elasticsearch 7.5.1 will start fine. 

**Conclusion**
It was a cool plugin but unfortunately it needs some updates that are out of my competencies zone.

**Comment by anandnalya** [comment]
Released a [new version](https://github.com/Automattic/elasticsearch-statsd-plugin/releases/tag/7.0.0.0) compatible with ES 7.0.0. You should now be able to compile it for later ES versions.
