### ISSUE TITLE
Can't start in docker environment

### ISSUE THREAD

**Issue by Ulrhol** [Automattic/elasticsearch-statsd-plugin#6]
When I start the plugin in elasticsearch:2.3.0 it fails with the following message:

```
Exception in thread "main" org.elasticsearch.common.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, com.timgroup.statsd.StatsDClientException: Failed to start StatsD client
  at com.automattic.elasticsearch.statsd.StatsdService.<init>(Unknown Source)
  while locating com.automattic.elasticsearch.statsd.StatsdService

1 error
Likely root cause: java.lang.IllegalArgumentException: hostname can't be null
        at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:113)
        at com.timgroup.statsd.NonBlockingStatsDClient.<init>(NonBlockingStatsDClient.java:82)
        at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:88)
        at com.automattic.elasticsearch.statsd.StatsdService$1.run(StatsdService.java:85)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.automattic.elasticsearch.statsd.StatsdService.<init>(StatsdService.java:85)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.start(Node.java:255)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

This seems to be a problem for many java projects. Maybe related to localhost ::1 address but I've tried to change the /etc/hosts file in a lot of different ways but no luck. I used the exact same config outside of docker and it works.

**Comment by arthurlogilab** [comment]
Getting this same bug. @Ulrhol have you found a fix ?

**Comment by Ulrhol** [comment]
No. I gave up and started using jmxtrans to read metrics from JMX instead. Not an elegant solution and I'm not sure I can get the same/equivalent metrics but I read a few key metrics that gives me some insight.

**Comment by nbrownus** [comment]
I fixed this by manually specifying `metrics.statsd.host: 127.0.0.1` in my es config
